services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: php-debug:latest
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
      - "8000:8000"
    environment:
      PMA_HOST: db
    volumes:
      - .:/var/www/html
      - composer_cache:/root/.composer/cache
    working_dir: /var/www/html

volumes:
  db_data:
  composer_cache:
